version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=grocery
      - DB_USER=root
      - DB_PASSWORD=Password123##
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123##
      MYSQL_DATABASE: grocery
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
